### ISSUE TITLE
测试节点一直打印这个错误是啥问题啊？

### ISSUE THREAD

**Issue by xiaoGreaat** [nebulasio/wiki#224]
`ReferenceError: title is not defined
    at EggContract.save (lib/contract.js:85:19)
    at _contract_runner.js:5:29  file=logger.go func=nvm.V8Log line=32
ERRO[2018-09-21T08:54:11+08:00] V8 Exception:
lib/contract.js:85
            title:title,
                  ^
ReferenceError: title is not defined
    at EggContract.save (lib/contract.js:85:19)
    at _contract_runner.js:5:29  file=logger.go func=nvm.V8Log line=32
ERRO[2018-09-21T08:54:41+08:00] V8 Exception:
lib/contract.js:85
            title:title,
                  ^
ReferenceError: title is not defined
    at EggContract.save (lib/contract.js:85:19)
    at _contract_runner.js:5:29  file=logger.go func=nvm.V8Log line=32
ERRO[2018-09-21T08:54:41+08:00] V8 Exception:
lib/contract.js:85
            title:title,
                  ^
ReferenceError: title is not defined
    at EggContract.save (lib/contract.js:85:19)
    at _contract_runner.js:5:29  file=logger.go func=nvm.V8Log line=32
ERRO[2018-09-21T08:55:11+08:00] V8 Exception:
lib/contract.js:85
            title:title,
                  ^
ReferenceError: title is not defined
    at EggContract.save (lib/contract.js:85:19)
    at _contract_runner.js:5:29  file=logger.go func=nvm.V8Log line=32
ERRO[2018-09-21T08:55:11+08:00] V8 Exception:
lib/contract.js:85
            title:title,
                  ^
ReferenceError: title is not defined
    at EggContract.save (lib/contract.js:85:19)
    at _contract_runner.js:5:29  file=logger.go func=nvm.V8Log line=32
`

**Comment by Samuelchen85** [comment]
这是V8执行智能合约时候报的错误，是合约自身的问题，并不会影响同步。

**Comment by xiaoGreaat** [comment]
@Samuelchen85  如果节点一直同步一个区块 那是啥问题啊？

**Comment by Samuelchen85** [comment]
有更多的日志信息么？在哪个区块不动了？

**Comment by weiht12** [comment]
你好，此版本为星云旧版wiki（后期逐步停止维护），欢迎将您的问题提交星云新版wiki，以便于获得及时解答。同时，参与wiki的编辑维护工作还会有奖励哦。新版wiki链接：https://wiki.nebulas.io/en/latest/（英文）；https://wiki.nebulas.io/zh_CN/latest/（中文）
Hello, this version is the nebulas old wiki (later stop maintenance), welcome to submit your question to the new nebulas wiki, in order to get timely answers. At the same time, there will be rewards for editing and maintaining the wiki. New wiki link: https://wiki.nebulas.io/en/latest/(English); https://wiki.nebulas.io/zh_CN/latest/(Chinese)
