### ISSUE TITLE
./neb account new  错误

### ISSUE THREAD

**Issue by includeleec** [nebulasio/wiki#81]
`
$ ./neb account new
Your new account is locked with a passphrase. Please give a passphrase. Do not forget this passphrase.
Passphrase:
Repeat passphrase:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xa6c502]

goroutine 1 [running]:
github.com/nebulasio/go-nebulas/core.(*Address).String(0x0, 0xc4200149b0, 0x5)
        /home/ubuntu/workspace/blockchain/src/github.com/nebulasio/go-nebulas/core/address.go:138 +0x22
main.accountCreate(0xc420012b00, 0x0, 0x0)
        /home/ubuntu/workspace/blockchain/src/github.com/nebulasio/go-nebulas/cmd/neb/accountcmd.go:109 +0xf6
main.MergeFlags.func1(0xc420012b00, 0x0, 0xc420012b00)
        /home/ubuntu/workspace/blockchain/src/github.com/nebulasio/go-nebulas/cmd/neb/flags.go:356 +0x103
github.com/nebulasio/go-nebulas/vendor/github.com/urfave/cli.HandleAction(0xceb220, 0xc4201af720, 0xc420012b00, 0xc420062500, 0x0)
        /home/ubuntu/workspace/blockchain/src/github.com/nebulasio/go-nebulas/vendor/github.com/urfave/cli/app.go:490 +0xd2
github.com/nebulasio/go-nebulas/vendor/github.com/urfave/cli.Command.Run(0xe36a0b, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0xe458be, 0x14, 0x0, ...)
        /home/ubuntu/workspace/blockchain/src/github.com/nebulasio/go-nebulas/vendor/github.com/urfave/cli/command.go:210 +0xa95
github.com/nebulasio/go-nebulas/vendor/github.com/urfave/cli.(*App).RunAsSubcommand(0xc42006d1e0, 0xc420012840, 0x0, 0x0)
        /home/ubuntu/workspace/blockchain/src/github.com/nebulasio/go-nebulas/vendor/github.com/urfave/cli/app.go:379 +0xa7b
github.com/nebulasio/go-nebulas/vendor/github.com/urfave/cli.Command.startApp(0xe39cb2, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0xe40fe6, 0xf, 0x0, ...)
        /home/ubuntu/workspace/blockchain/src/github.com/nebulasio/go-nebulas/vendor/github.com/urfave/cli/command.go:298 +0x944
github.com/nebulasio/go-nebulas/vendor/github.com/urfave/cli.Command.Run(0xe39cb2, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0xe40fe6, 0xf, 0x0, ...)
        /home/ubuntu/workspace/blockchain/src/github.com/nebulasio/go-nebulas/vendor/github.com/urfave/cli/command.go:98 +0x1319
github.com/nebulasio/go-nebulas/vendor/github.com/urfave/cli.(*App).Run(0xc42006cd00, 0xc420010090, 0x3, 0x3, 0x0, 0x0)
        /home/ubuntu/workspace/blockchain/src/github.com/nebulasio/go-nebulas/vendor/github.com/urfave/cli/app.go:255 +0x6f8
main.main()
        /home/ubuntu/workspace/blockchain/src/github.com/nebulasio/go-nebulas/cmd/neb/main.go:76 +0xaa0
`

**Comment by act262** [comment]
u should deploy your local server firstly, and  then use  those`admin` command.
